# https://www.gitpod.io/docs/introduction/learn-gitpod/gitpod-yaml

#image:
 #   file: .gitpod.Dockerfile

tasks:
# Test install CLI via dockerfile to persist between workspace restarts
  - name: install packages, overwrite example schema, run migrations, open files
    before: echo 'before'
    init: |
      gp open installing.md
      yarn
      curl --proto '=https' --tlsv1.2 -sSf https://sh.edgedb.com | sh -s -- -y -v
      edgedb project init --non-interactive
      mv default.esdl dbschema
      edgedb migration create --non-interactive && edgedb migration apply && yarn generate
    command: |
      test -e /home/gitpod/.local/bin && echo 'hello' || curl --proto '=https' --tlsv1.2 -sSf https://sh.edgedb.com | sh -s -- -y -v ; edgedb project init --server-instance=edgedb --non-interactive
      echo 'opening welcome'
      gp open welcome.md
vscode:
  extensions:
    - matt-rudge.auto-open-preview-panel
#     - https://github.com/edgedb/edgedb-editor-plugin/issues/22 (schema syntax highlighting unavailable until VScode extension published to OpenVSX)

