# https://www.gitpod.io/docs/introduction/learn-gitpod/gitpod-yaml

tasks:
  - name: install packages, overwrite example schema, run migrations, open files
    before: npm install -g npm@latest
    init: |
      gp open welcome.md
      npm i
      curl --proto '=https' --tlsv1.2 -sSf https://sh.edgedb.com | sh -s -- -y -v
      edgedb project init --non-interactive
      mv default.esdl dbschema
      edgedb migration create --non-interactive && edgedb migration apply
      npm run generate
      yarn seed
      gp open dbschema/default.esdl
    command: |
      if test -e /home/gitpod/.local/bin/edgedb; then echo 'EdgeDB CLI installed successfully' && gp open src/index.ts; else gp open restart.md && curl --proto '=https' --tlsv1.2 -sSf https://sh.edgedb.com | sh -s -- -y -v && edgedb project init --server-instance=edgedb --non-interactive && yarn seed ; fi
vscode:
  extensions:
    - matt-rudge.auto-open-preview-panel
    - esbenp.prettier-vscode
    - bungcip.better-toml
    #- magicstack.edgedb (schema syntax highlighting unavailable until VScode extension published to OpenVSX https://github.com/edgedb/edgedb-editor-plugin/issues/22 )
